version: '3.8'

services:
  app:
    build:
      context: .
    container_name: dotportal-app
    volumes:
      - .:/app
    environment:
      - DB_DSN=postgres://postgres:postgres@db:5432/broker_portal?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - broker-net

  db:
    image: postgres:15
    container_name: broker-db
    restart: always
    environment:
      POSTGRES_DB: broker_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - broker-net

volumes:
  pgdata:

networks:
  broker-net:
